# Generated by Django 5.1 on 2024-12-03 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('market_cap', models.FloatField(null=True)),
                ('pe_ratio', models.FloatField(null=True)),
                ('eps', models.FloatField(null=True)),
                ('dividend_yield', models.FloatField(null=True)),
                ('revenue', models.FloatField(null=True)),
                ('profit_margin', models.FloatField(null=True)),
                ('operating_margin', models.FloatField(null=True)),
                ('return_on_assets', models.FloatField(null=True)),
                ('return_on_equity', models.FloatField(null=True)),
                ('debt_to_equity', models.FloatField(null=True)),
                ('current_ratio', models.FloatField(null=True)),
                ('quick_ratio', models.FloatField(null=True)),
                ('sector_encoded', models.IntegerField(null=True)),
                ('cluster_kmeans', models.IntegerField(null=True)),
                ('cluster_gmm', models.IntegerField(null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='comparables.company')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('adj_close', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('open', models.FloatField(null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='comparables.company')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
